#!/usr/bin/env bash
# Script that displays "Best School" from 1 to 10
#   "bad luck" at 4th iteration
#   "good luck" at 8th iteration

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
